---
- name: Run IICS-specific and Azure tasks on localhost
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Get storage account details for fileshare
    azure_rm_storageaccount_info:
      tags:
        - Usage:Fileshare
      show_connection_string: true
    register: result_storage

- name: mount-azurefiles
  hosts: all
  roles:
    - role: mount-azurefiles
      stg_account_name: "{{ hostvars.localhost.result_storage.storageaccounts[0].name }}"
      stg_account_key: "{{ hostvars.localhost.result_storage.storageaccounts[0].primary_endpoints.key }}"
      stg_fileshare_name: "iicsshare"
      mount_point: "{{ mount_path }}"
      win_mount_letter: "z"
      become: yes